swagger: '2.0'

info:
  version: "1.0.0"
  title: IttruSystem
  description: Micro-serviço para listar documentos, obter o hash, salvar assinaturas e visualizar PDFs compatível com o sistema Ittru Fusion.

host: ittrufusion.appspot.com
basePath: /testsigner/api/v1
schemes: [http,https]
consumes: [application/json]
produces: [application/json]

tags:
  - name: view
    description: Listar os documentos a serem assinado e visualizar os PDFs
  - name: sign
    description: Obter o hash e gravar a assinatura digital
  - name: auth
    description: Verificar a autenticidade de um documento

paths:
  /doc/list:
    get:
      description: Obter a lista de documentos a serem assinados pelo usuário portador do CPF informado
      tags: [view,sign]
      parameters:
        - $ref: "#/parameters/cpf" 
        - $ref: "#/parameters/urlapi" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/Document"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/pdf:
    get:
      description: Obter o PDF de um documento para visualização
      tags: [view]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/cpf" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              doc:
                type: string
                format: byte
                description: PDF codificado em base64
              secret:
                type: string
                description: Segredo associado ao documento que será validado para permitir a visualização
            example:
              doc: 24yd3pPUpPz4dyVdRQAP+zI7R8wTsNX9J7El/a5Bb64=
              secret: 05d50c47-0ed5-4fb0-80c7-ea65d37d27a0
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/hash:
    get:
      description: Obter o hash de um documento
      tags: [sign]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/cpf" 
        - $ref: "#/parameters/extra" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              sha1:
                type: string
                format: byte
              sha256:
                type: string
                format: byte
              policy:
                type: string
              extra:
                type: string
              doc:
                type: string
                format: byte
              secret:
                type: string
                description: Segredo associado ao documento que será validado para permitir o envio do conteúdo do PDF para ser assinado em PKCS7
            example:      
              sha1: csTZGGSt1AG1m3T5VaIzcHX8Av0=
              sha256: 24yd3pPUpPz4dyVdRQAP+zI7R8wTsNX9J7El/a5Bb64=
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/sign:
    put:
      description: Gravar a assinatura do documento
      tags: [sign]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/cpf" 
        - $ref: "#/parameters/name" 
        - $ref: "#/parameters/time" 
        - $ref: "#/parameters/sha1" 
        - $ref: "#/parameters/extra" 
        - $ref: "#/parameters/envelope" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
              warning:
                type: array
                items:
                  $ref: "#/definitions/Warning"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/info:
    get:
      description: Obtem as assinaturas e as movimentações do documento
      tags: [auth]
      parameters:
        - $ref: "#/parameters/id"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
              signature:
                type: array
                items:
                  $ref: "#/definitions/Signature"
              movement:
                type: array
                items:
                  $ref: "#/definitions/Movement"
              secret:
                type: string
                description: Segredo associado ao documento que será validado para permitir a visualização
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
            
  /sign/{ref}:
    get:
      description: Obter uma assinatura de um documento
      tags: [auth]
      parameters:
        - $ref: "#/parameters/ref"
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              envelope:
                type: string
                format: byte
                description: Envelope da assinatura codificado em base64
              time:
                type: string
                format: date-time
                description: Data e hora da assinatura
            example:
              envelope: 24yd3pPUpPz4dyVdRQAP+zI7R8wTsNX9J7El/a5Bb64=
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
parameters:
  id:
    name: id
    in: path
    description: Identificador do documento
    required: true
    type: string
  ref:
    name: ref
    in: path
    description: Identificador da assinatura
    required: true
    type: string
  cpf:
    name: cpf
    in: query
    description: CPF do usuário
    required: true
    type: string
  urlapi:
    name: urlapi
    in: query
    description: DEPRECATED - URL que foi usada para chamar a API.
    required: false
    type: string
  sha1:
    name: sha1
    in: formData
    required: false
    type: string
    format: byte
  name:
    name: name
    in: formData
    required: false
    type: string
  time:
    name: time
    in: formData
    required: false
    type: string
    format: date-time
  envelope:
    name: envelope
    in: formData
    description: Envelope CMS/PKCS7 codificado em base64
    required: true
    type: string
    format: byte
  extra:
    name: extra
    in: formData
    required: false
    type: string

            
definitions:
  Document:
    type: object
    properties:
      id:
        type: string
        description: identificador do documento
      secret:
        type: string
        description: segredo associado ao documento, se não for informado, qualquer pessoa poderá visualizar seu PDF. Deve ser usada uma senha bem grande, de preferência, um GUID ou um SHA256.
      code: 
        type: string
      descr: 
        type: string
      kind: 
        type: string
      origin: 
        type: string
      extra: 
        type: string
    example:
      id: 00489623760_2_67631650_1460490840000_0_0
      code: 0100222-90.2014.4.02.0000
      descr: Conclusão para Decisão  -  Concedida a Antecipação de tutela
      kind: Decisão
      origin: TextoWeb
      extra: 1

  Signature:
    type: object
    properties:
      ref:
        type: string
      signer:
        type: string
      kind:
        type: string

  Movement:
    type: object
    properties:
      time:
        type: string
        format: date-time
      department:
        type: string
      kind:
        type: string

  Warning:
    type: object
    properties:
      label:
        type: string
      description:
        type: string

  ErrorDetail:
    type: object
    properties:
      service:
        type: string
      context:
        type: string
      stacktrace:
        type: string
      url:
        type: string
      presentable:
        type: boolean
      logged:
        type: boolean

  Error:
    type: object
    properties:
      errormsg:
        type: string
      errordetails:
        type: array
        items:
          $ref: "#/definitions/ErrorDetail"